### PR TITLE
Added support for a separate Status domain export

### PR DESCRIPTION
**Pull request by abouffard**
Addresses part of issue #200
Corrects file names of special entity exports
Please note change in name of "Planned" to "Planned/Anticipated/Suspect"

User's can't usually "plan" for hostile units to be at a particular
location.  User's can mostly only "anticipate" or "suspect" that hostile
units will be somewhere at sometime.

### CODE REVIEW

**Comment by csmoore** [comment]
Isn't that how it was stated in #200 ?

**Comment by wmcgrane** [comment]
Logical....

-----Original Message-----

**Comment by abouffard** [comment]
@csmoore , yes, but not how it was originally implemented for status/operational condition for JMSML 1.0.  The domain value has been "Present" or "Planned" (where "Planned" inferred anticipation or suspicion).  Now we are explicitly referring to all three concepts in the new name.  

I was just noting the change for status and operational condition to "Present" and "Planned/Anticipated/Suspect".

**Comment by wmcgrane** [comment]
Is a CP really necessary for something that appears to me to be a programming requirement and not a CM issue of the standard?

Bill

-----Original Message-----

**Comment by abouffard** [comment]
No.  We're not suggesting a CP for this.  We're making JMSML better reflect what is in the standard..

**Pull request merged**
