### PR TITLE
Adding export of schema metadata

### PR DESCRIPTION
**Pull request by abouffard**
With the right GP tool, to be built in the military features data repo, this metadata can be used to build empty feature classes in a military feature geodatabase.

### CODE REVIEW

**Comment by abouffard** [comment]
@csmoore , please give the exported results a once over.  The data here should be identical to the current feature class details found [here](https://github.com/Esri/military-features-data/blob/master/data/mil2525d/core_data/gdbs/MilitaryOverlay.gdb.zip).

As with the Fields, there are discrepancies/inconsistencies in our feature class aliases.  I propose a quick review and clean up of these in the next iteration of this work, so our feature classes look a little "cleaner"..

**Comment by csmoore** [comment]
Data looks good to me, the only thing I would prefer to be changed is that the name "schemas.csv" changed to something more descriptive(&consistent with the other data in that folder) like "FeatureClass_Schemas.csv" 

Also, I'm not sure how nice this format will play with the CreateFeatureClass and ImportMetaData GP Tools so hopefully you have a plan for that (ex: The CreateFeatureClass tool uses "Polyline" instead of "Line").  In the case of the Domain and Field csv exports these formats matched *exactly* what the GP tools used so the GDB imports were straightforward, but I don't see that with this FeatureClass format so *if a lot of custom code will be required to use this format*, then you may want to reconsider (or do a simple working prototype if you haven't already done so).

**Comment by abouffard** [comment]
Thanks for the feedback, @csmoore .  I did carefully consider the terms I used, both to name the new export file and its contents.

In my interest to keep the stuff in JMSML as implementer agnostic as possible/reasonable, I felt the naming of the file as Schemas.csv matched a pattern well enough (since the data is stored as a set of "schemas" in the JMSML config database).  Thus...

Schemas.csv

Fields_Activities.csv
Fields_Air.csv
etc....

Subtypes_Air.csv
Subtypes_Cyberspace.csv
etc...

The terms Line and Area (versus Polyline and Polygon) also match the geometric terms used in the standards and everywhere else in the JMSML XML data.

I think a little conversion code in the GP tool can handle translating "ControlMeasureLines Line Schema" to "ControlMeasureLines Polyline Featureclass" without too much "custom code".

Rather than introduce Esri GIS terms like "Polyline FeatureClass" into stuff stored or produced by JMSML one of whose design goals is to make it palatable to all military symbology implementers and, in so doing, encourage DISA to assume more ownership of it, I'd much rather split the joint-military-symbology-xml repo up and create a purely Esri-centric joint-military-symbology-tools repo that contains all the C# code and sample exports.  With a split like that I wouldn't care how many Esri "GISisms" we put into the JMSMLtools repo, because the XML and SVG files would then live separately and be purely implementer agnostic.

**Comment by abouffard** [comment]
@csmoore In light of my above comment, and given that I'd like to create a new version 1.01 before the current sprint ends, and knowing that once the GP tools are being built, engineering and testing will probably lead to needed tweaking of the exports from JMSML, please go ahead and merge this PR.  I don't intend to make any changes in the next 24 hours and I don't want to buck protocol (letting the reviewer perform the merge) by merging it myself.

**Comment by wmcgrane** [comment]
Concur.

Bill McGrane
Chair, Symbology Standards Management Committee
DISA BDC/EE212
Messaging Standards Section
Ft. Meade, MD
301-225-7383




-----Original Message-----

**Comment by csmoore** [comment]
Assigned this PR back to @abouffard - since it sounds like he is more familiar with the goals, suitability, etc. of this so I'm probably not the best person to review this. My comments were related specifically to getting to a working geodatabase this sprint - which is my main concern. I'm less concerned with the intermediate formats required to get there.

**Pull request merged**
