### PR TITLE
Final 2525C SVG Resizing/Bug Fixes

### PR DESCRIPTION
**Pull request by Dbarnes1**
Resized the remainder of the legacy SVGs
In this PR are mainly
-SIGINT symbols
-Remaining full-frame symbols
-edits to remaining bugs in land-units.xml

### CODE REVIEW

**Comment by Dbarnes1** [comment]
@abouffard @csmoore This should do it for this round of SVG edits

**Comment by Dbarnes1** [comment]
@abouffard @csmoore This should do it for this round of SVG fixes. There may be remaining bugs/errors but hopefully a stylx built with these SVGs will render the symbols properly.

**Comment by abouffard** [comment]
You're a good man Charlie "@Dbarnes1" Brown.

**Comment by abouffard** [comment]
@Dbarnes1 , did you also fix all those XML issues?

**Comment by Dbarnes1** [comment]
Hopefully all of them, I went through the military-all-icons.csv and fixed between 10-15 errors in XML. Two "instance" xml files are in this PR as a result

**Pull request merged**
