### PR TITLE
Updated legacy symbol creation Readme

### PR DESCRIPTION
**Pull request by BobBooth**
Updated legacy symbol creation Readme to reflect revised process that preserves page space/alignment.

### CODE REVIEW

**Comment by BobBooth** [comment]
@abouffard & @Dbarnes1 - I've updated the readme instructions for legacy symbol creation. Please review and merge.

**Comment by Dbarnes1** [comment]
@BobBooth @abouffard I reviewed this commit and everything looks good- I'll go ahead and merge. Thanks for taking care of this before we forgot about it!

**Comment by Dbarnes1** [comment]
Actually, content is good but do we want to merge changes into the dev branch? @abouffard

**Comment by abouffard** [comment]
@Dbarnes1 , yes we should merge this with dev.

**Comment by abouffard** [comment]
@BobBooth , can you please close this and re-submit it to the dev branch?  Thanks.

**Pull request closed without merging**
