### PR TITLE
Updates to feature class/field/domain files for Mil2525c schema

### PR DESCRIPTION
**Pull request by csmoore**
These were the updates used to create a 2525C version of Military Overlay that works similar to 2525D.

We will keep this PR open until we have validated that these fields/domains/etc. are correct.

We can also discuss later if/how we might be able to update this in the source data.

### CODE REVIEW

**Comment by csmoore** [comment]
These 2525C tables have been validated and are ready to merge into their own branch (until it is determined how to better support both the 2525D and 2525C schemas) - assigning to @abouffard to merge

**Comment by abouffard** [comment]
A quick perusal and merge.

**Comment by csmoore** [comment]
@abouffard - while you are looking at the changes required to [remove the schema subtypes](https://github.com/Esri/joint-military-symbology-xml/issues/269) - it would be useful to know if/when we can ever expect this repo to support the 2525C (and possibly later 2525B) schema included in this PR - if we will still maintain 2525C & 2525B csv's/schema's manually that might inform our decision on whether we even need to continue to maintain/update the schema source data in JMSML

**Comment by abouffard** [comment]
Yes, @csmoore , JMSML could support multiple database schemas and output CSVs for as many different schemas as we require.  I would estimate it would take a day to make any changes needed to ensure the export of CSV files for multiple database schemas worked as desired, then probably half a day to a day to populate the schema XML with the details for 2525C and 2525Bc2.  Since all three schemas (2525Bc2, 2525C, and 2525D) share much of the same structure, and given the way the JMSML schema XML has been set up, much of the field/column details for attributes common to all three schemas is already entered and can easily be shared between them.

I do agree with @Dbarnes1 that these modifications to JMSML needn't take priority away from finishing the legacy renderers first.  Waiting to capture the final geodatabase schemas inside JMSML near the end of the DCGS-A project, or even afterward as a post-delivery administrative task, wouldn't be a bad thing as it would ensure that the geodatabase schemas have been thoroughly tested against current capability and any capabilities we still need to build for DCGS-A.

**Pull request merged**
