### PR TITLE
Legacy fixes in late June 2016

### PR DESCRIPTION
**Pull request by abouffard**
The fixes in this PR result in JMSML being able to produce CSV output that is physically equivalent and/or functionally equivalent to the CSV found in these two PRs.

https://github.com/Esri/joint-military-symbology-xml/pull/317

https://github.com/Esri/joint-military-symbology-xml/pull/275

### CODE REVIEW

**Comment by csmoore** [comment]
From a quick check, I am seeing numerous differences in this version of the legacy output versus the mapping provided in #317 . 

1. Different number of entries/rows

2. Alternate mappings that will not produce a symbol (because this symbol does not exist in lines-areas-labels-template.stylx):
image
3. Missing mappings:
image
4. Repeated C, B2 entries even though no difference in mapping:
image

Please come up with a test method to verify this sprint that the files in this PR are "functionally equivalent" since they do not appear that they will produce an equivalent style

**Comment by abouffard** [comment]
@csmoore - please review if/when you have time.  When able over the next week I will review any comments you may have.  Assuming my verification found under https://github.com/csmoore/mil2525-testing/pull/1 is acceptable for the end of DCGS-A Milestone 3, I intend to merge this PR with minimal further change and then update master from dev.  I also intend to use this PR to close out changes to JMSML and then create version 1.0.4 from its master.

**Comment by csmoore** [comment]
I'm still seeing a significant number of differences when comparing the before/after tables:

image

These still may well be legitimate mappings, but we'll need to wait until the next test/release cycle to verify this source given the extra time it took to produce/correct this source data (i.e. done after the dependent styles were tested/complete).  @Dbarnes1 - if/when we update the legacy styles we should factor in a couple extra days to do this independent verification.

This is fine to merge as far as I'm concerned - other than a before/after text diff there is not much else I can add to reviewing these changes - but @Dbarnes1 / @joebayles should have a look

**Comment by joebayles** [comment]
Discussed w/ @Dbarnes1 
We will merge this pull request, re-run the diff tests, and reassess.

**Comment by abouffard** [comment]
Thank you @Dbarnes1 and @joebayles .

**Comment by csmoore** [comment]
Note: if we are talking about the image diff tests (that @abouffard already ran/mentioned above in https://github.com/csmoore/mil2525-testing/pull/1 ) - this is only part of the testing/dependencies of the legacy styles and military schemas. Checking the comprehensive test dataset in ArcGIS and (re)generating the domains/lpks also being part of this, so that should be included as well.

I want to mention the actual check in ArcGIS Desktop since there are quite a few things that the image test alone won't catch (ex. a missing line/polygon symbol) - particularly important with the deltas I observed between what was produced here and what was actually requested in https://github.com/Esri/joint-military-symbology-xml/pull/317 

Feel free to do this repo re-check on slack time or as I mentioned above we can plan this into our project if/when we actually need to re-create the legacy style.

**Comment by Dbarnes1** [comment]
@joebayles correct me if otherwise, but I think him and I are going to tackle that on slack time so we can focus on the milestone 4 deliverables for DCGS-A.

**Pull request merged**
