### PR TITLE
Adding 2525C SVG's

### PR DESCRIPTION
**Pull request by Dbarnes1**
I'm opening this pull request as I add the legacy SVG's for 2525C. There are also some changes to the xml files as I find any remaining typos.

### CODE REVIEW

**Comment by Dbarnes1** [comment]
@csmoore @abouffard I opened up this pull request and will continue to make commits as I complete more SVG's for 2525C. I will let you know when to review and merge, but I'm not done creating the SVG's yet.

**Comment by Dbarnes1** [comment]
Ok @abouffard I'm ready for a review of these SVG's, Hopefully they are good to go and once @BobBooth creates a PR for the appendices that he is working on (space, space missile, sea surface and subsurface) we can create a stylx and start any bug fixing if necessary.

**Comment by abouffard** [comment]
Thanks @Dbarnes1 .  @BobBooth emailed me some of his SVGs to test so I will combine yours with his and see how they look.

**Comment by abouffard** [comment]
@Dbarnes1 and @BobBooth , I think we need to talk...  I pulled Daniel's SVGs down to a local branch to have a look and I think we have to revisit the process.  Something you both did resulted in icons that are much larger than the others that have been created.  

I followed a procedure that seemed to result in a smaller icon, more in keeping with the size of the others.  I think we need to work together to find a common approach that gives good results.  Now that I have Illustrator on my machine too, lets meet today (Thursday morning) to share screens and experiences.

There are also a few that have issues besides size.

image

image

image

**Comment by csmoore** [comment]
@Dbarnes1 @abouffard @BobBooth 

I would agree those SVGs don't look *anything* like when I did the legacy ones originally. **Please include me in this planned meeting**

I only checked this one - https://raw.githubusercontent.com/Dbarnes1/joint-military-symbology-xml/master/svg/MIL_STD_2525D_Symbols/Legacy/2525C/S-G-UUMSEJ_0.svg and it has numerous significant issues that should be rectified:

1. Different reference/viewbox
2. Missing reference frame/octagon layer with display/visible set to false (that would make checking this size much easier).
3. Odd clipping code
4. Use of "ArialMT" font ( @abouffard had a prior action to tell us how DISA handles this font issue and is able to map these to "san-serif")

The original process was hopefully simple enough (but maybe the changes in the readme since I worked on in January didn't make this original process clear):

1. Copy the template frame/octagon **file** and rename it ( this will now have the correct viewbox reference size and frame/octagon reference layer )
2. Copy/paste the desired legacy icon into this new/renamed file
3. Turn off visibility for the frame/octagon reference layer and save

**Comment by Dbarnes1** [comment]
@abouffard @csmoore just committed some new symbols, I think they should be sized correctly. I'll keep plugging away.

**Comment by Dbarnes1** [comment]
@abouffard I resized most of the SVG's. There are still bugs and improper svgs that need fixing, but you should be able to load a stylx and view that the majority of the symbols are rendering correctly. I think I'll be able to complete the rest tomorrow morning.

**Comment by abouffard** [comment]
While there is still work to be done, I'm going to merge these in and build a stylx for testing and do it again when @Dbarnes1 has fixed more of these.

**Pull request merged**
