### PR TITLE
Fixes to #296 and other Legacy Edits

### PR DESCRIPTION
**Pull request by Dbarnes1**

### CODE REVIEW

**Comment by Dbarnes1** [comment]
fixes #296

**Comment by Dbarnes1** [comment]
Fixes to #297  as well @abouffard this is ready to verify and merge

**Comment by abouffard** [comment]
@Dbarnes1 , I'm in the middle of reviewing this, but realized it was a PR made against master.  Now that I have created the dev branch we want to start working against that.  If I merge this against master I'll also have to make sure dev is updated.  We can discuss after scrum.

**Comment by Dbarnes1** [comment]
@abouffard whoops, I was aware that there were changes to the branches but I forgot to change my github workflow to reflect that.

**Comment by abouffard** [comment]
@Dbarnes1 - I'd prefer if you could close this and re-submit under dev, if you can.

**Pull request closed without merging**
