### PR TITLE
Added a deployable version of the jmsml console application

### PR DESCRIPTION
**Pull request by abouffard**

### CODE REVIEW

**Comment by abouffard** [comment]
@Dbarnes1 , please test this or have @BobBooth test this, to make sure that you both can follow the README instructions here and run the batch files found under JMSML's samples sub-folders.  If this makes sense and works for you then I will merge this PR Monday night.

**Comment by Dbarnes1** [comment]
@abouffard looks good, ready to merge.

**Comment by csmoore** [comment]
Would it be possible to just include the unzipped files with the repo - rather than as a zip? That way things will just work when you clone without the additional unzip steps. 

Also, it seems odd that this is the "Debug" deployment version. Can we switch this to the "Release" ?

**Comment by abouffard** [comment]
I had originally planned to include just the unzipped files, until I remembered we already had something similar here https://github.com/Esri/military-features-data/blob/master/data/mil2525d/utilities/style-utilities/style-file-utilities/csv2ArcGISStyleDeployment.zip and decided to remain consistent.  I'll be happy to switch to individual files if that is what everyone would prefer.

This will remain in "Debug" mode as long as we are in the "dev" branch.  In my mind "dev" means we are under development and subject to change and subject to the need to debug the underlying code.  The various batch files use relative paths inside them to run the console app, and in "dev" they are pointing to this "Debug" folder.  When we merge this branch to "master" I will change this to "Release" and adjust the batch files accordingly.

**Comment by csmoore** [comment]
I don't recall seeing such a discussion but, yes, please switch to an unzipped version - the csv2ArcGISStyleDeployment.zip is a bit different in that it has numerous external dependencies (external products/dlls and files that need to be edited) - where as this utility can just run as-is from this repo/clone. I also think a lesson-learned from csv2ArcGISStyleDeployment.zip is that was just one more thing/step that could break.

You may also want to reconsider the complexity of the debug-release dev-master process proposed in the comment above.

**Comment by abouffard** [comment]
Closed to revisit and revise the approach.

**Pull request closed without merging**
