### PR TITLE
Updates from testing

### PR DESCRIPTION
**Pull request by csmoore**
Just opening this PR to have Dan review - no need to merge until we are finished testing/stabilizing GDB

### CODE REVIEW

**Comment by Dbarnes1** [comment]
@csmoore after reviewing this PR everything looks good.

**Comment by csmoore** [comment]
Dan reviewed and tested these changes in the GDB, so this is ready to merge into this branch - assigning to @abouffard

**Comment by csmoore** [comment]
One thing I wanted to point out, and this might just be lack of familiarity on my part, but I could not readily see the relationship between these output schema csv's and the inputs/apps/steps required to produce these csv's, so in the interest of time I had to edit the output csv's directly.

I'm not sure @Dbarnes1 or I could modify this config file directly: https://github.com/Esri/joint-military-symbology-xml/blob/master/source/JointMilitarySymbologyLibraryCS/jmsml.config to make these types of changes&produce this output unless there are some instructions/steps I didn't find. The only instructions I found were here: https://github.com/Esri/joint-military-symbology-xml/tree/master/samples#schemas (and I'm not sure Dan would be expected to build that app - is there a deployed version somewhere also?)

**Comment by abouffard** [comment]
No there is no deployed version of that app but there could of course be.  That app is the app that builds all the csv files.  Running [this] (https://github.com/Esri/joint-military-symbology-xml/blob/master/RunAll.bat) file runs all the batch files in the sub folders of [samples](https://github.com/Esri/joint-military-symbology-xml/tree/master/samples).

I always run these batch files to regenerate the csvs after making changes to the code or xmls.

I'm happy to educate @Dbarnes1 on how to modify the XML.  That is the only real best choice because a running of those batch files will replace everything.  

Until or if he becomes comfortable enough to edit the XML himself, we could proceed with him raising an issue for changes he wants to make and I will make them and then rebuild the CSVs for him.

The alternative for now is that we can create a version of JMSML when we reach a steady state with this and he can manually edit the CSVs if he needs to but should capture what changes he makes in an issue so I can add to XML without slowing him down which would be reflected in a v.next.

I'll establish a v.next for my recent changes, which will include the CSVs I have, and I'll merge this PR as is into the master,

**Comment by abouffard** [comment]
Regarding instructions/steps.  No, other than the doc you cited, explaining how to use the jmsml console app, there is no XML doc yet for the config file.  It has yet to be written.

**Comment by csmoore** [comment]
As long as you don't mind us updating the csv's directly, which is straightforward to do, and you will update the XML to reflect this, and in a timely manner than we don't need any more guidance or doc. 

But that doesn't seem to have worked here (I made those updates last week, but perhaps we just need to refine & agree upon how this will work): https://github.com/Esri/joint-military-symbology-xml/blob/master/samples/name_domains_values/Coded_Domain_CountryCodes.csv

**Comment by abouffard** [comment]
Feel free to update any of the CSVs in non-master branches, but if you want any changes you make reflected in what JMSML exports from its XML source, and you don't want to submit a PR with changes to that XML source, then I'd suggest you document in an issue what you want added/changed.

I would rather not have to go through a bunch of CSV files submitted to a separate branch trying to find the differences between them and the master.  Sending me "diff" analysis through an issue will make it easier for me to see what you want changed and thus will speed my integration of your requested changes in the master.

Unless I'm missing something, I don't imagine we're talking about constant change anyway.

**Comment by csmoore** [comment]
Right, we don't *anticipate* many more changes - though @Dbarnes1 may have a few from his tech review & the jmslconfig seems rather mysterious to me, so I really just wanted to confirm we don't need to be expected to directly edit that - writing an issue sounds like a good solution to me - thanks

**Pull request merged**
